apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-server 
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: sparkyfitness-server-secret
    creationPolicy: Owner
    template:
      data:
        SPARKY_FITNESS_DB_NAME: sparkyfitness
        SPARKY_FITNESS_DB_USER: "{{ .SPARKYFITNESS_POSTGRES_USERNAME }}"
        SPARKY_FITNESS_DB_PASSWORD: "{{ .SPARKYFITNESS_POSTGRES_PASSWORD }}"
        SPARKY_FITNESS_DB_HOST: sparkyfitness-database.workloads.svc.cluster.local
        SPARKY_FITNESS_APP_DB_USER: "{{ .SPARKYFITNESS_POSTGRES_USERNAME_APP }}"
        SPARKY_FITNESS_APP_DB_PASSWORD: "{{ .SPARKYFITNESS_POSTGRES_PASSWORD_APP }}"
        SPARKY_FITNESS_FRONTEND_URL: fit.mrtb.io
        SPARKY_FITNESS_API_ENCRYPTION_KEY: "{{ .SPARKYFITNESS_API_ENCRYPTION_KEY }}"
        BETTER_AUTH_SECRET: "{{ .SPARKYFITNESS_BETTER_AUTH_SECRET }}"
        NODE_ENV: "production"
        TZ: "Europe/Berlin"
  dataFrom:
    - find:
        path: SPARKYFITNESS_ 
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"