apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: papra-secret
    creationPolicy: Owner
  data:
    - secretKey: encryptionkey
      remoteRef:
        key: PAPRA_ENCRYPTION_KEY
    - secretKey: authsecret
      remoteRef:
        key: PAPRA_AUTH_SECRET