---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: papra
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      papra:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/papra-hq/papra
              tag: 25.10.2-rootless@sha256:18c184620767ba1c240a5c1f3ef106430024dc6306607a6d2ac60b6ded3502e5
            env:
              DOCUMENT_STORAGE_ENCRYPTION_IS_ENABLED: "true"
              DOCUMENT_STORAGE_DOCUMENT_KEY_ENCRYPTION_KEYS:
                valueFrom:
                  secretKeyRef:
                    name: papra-secret
                    key: encryptionkey
              TRUSTED_ORIGINS: "https://docs.mrtb.io"
            resources:
              requests:
                cpu: 100m
                memory: 265Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
    service:
      app:
        controller: papra
        ports:
          http:
            port: &port 1221
    persistence:
      data:
        annotations:
          k8up.io/backup: "true"
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        advancedMounts:
          papra:
            app:
              - path: /app/app-data
    route:
      app:
        hostnames:
          - docs.mrtb.io
        parentRefs:
          - name: gateway
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: papra
                port: *port