apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kitchenowl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kitchenowl-secret
    creationPolicy: Owner
  data:
    - secretKey: KITCHENOWL_JWT_SECRET_KEY
      remoteRef:
        key: KITCHENOWL_JWT_SECRET_KEY
    - secretKey: KITCHENOWL_OPENAI_API_KEY
      remoteRef:
        key: KITCHENOWL_OPENAI_API_KEY