---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kitchenowl
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      kitchenowl-web:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: tombursch/kitchenowl
              tag: v0.7.4@sha256:9d5e4402c2abc734e1536586caa103840a7ebe961fdce1570e31b956abeba70b
            env:
              JWT_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: kitchenowl-secret
                    key: jwt-secret-key
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    service:
      web:
        primary: true
        controller: kitchenowl-web
        ports:
          http:
            port: &httpPort 8080
    persistence:
      data:
        annotations:
          k8up.io/backup: "true"
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        advancedMounts:
          kitchenowl-web:
            app:
              - path: /data
                subPath: kitchenowl
    route:
      app:
        hostnames:
          - kitchen.mrtb.io
        parentRefs:
          - name: gateway 
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: kitchenowl-web
                port: *httpPort