apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: sparkyfitness-database-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: 	SPARKYFITNESS_POSTGRES_PASSWORD
    - secretKey: username
      remoteRef:
        key: 	SPARKYFITNESS_POSTGRES_USERNAME