apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-workload-pvcs
  namespace: workloads
spec:
  backup:
    schedule: '0 */6 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '0 1 * * 1'
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 7
      keepDaily: 14