apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planka-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: planka-app-secret
    creationPolicy: Owner
  data:
    - secretKey: uri
      remoteRef:
        key: PLANKA_POSTGRES_URI
    - secretKey: key
      remoteRef:
        key: PLANKA_SESSION_KEY
    - secretKey: username
      remoteRef:
        key: PLANKA_USER_NAME
    - secretKey: password
      remoteRef:
        key: PLANKA_USER_PASSWORD