apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: planka-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: planka-database-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: 	PLANKA_POSTGRES_PASSWORD