---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: planka
spec:
  interval: 30m
  chart:
    spec:
      chart: planka
      version: 1.1.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: planka
  values:
    postgresql:
      enabled: false
    baseUrl: "https://tasks.mrtb.io"
    persistence:
      enabled: true
    existingSecretkeySecret: planka-app-secret
    existingAdminCredsSecret: planka-app-secret
    existingDburlSecret: planka-app-secret