---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workloads
resources:
  - ./backup/ks.yaml
  - ./code-server/ks.yaml
  - ./glance/ks.yaml
  - ./it-tools/ks.yaml
  - ./karakeep/ks.yaml
  - ./n8n/ks.yaml
  - ./papra/ks.yaml
  - ./unifi/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/alerts