---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
spec:
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: hcloud
      version:  0.2.0
  interval: 30m