apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8up
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: k8up-secret
    creationPolicy: Owner
  data:
    - secretKey: repopass
      remoteRef:
        key: K8UP_REPO_PASS
    - secretKey: s3accesskey
      remoteRef:
        key: K8UP_S3_ACCESS_KEY
    - secretKey: s3secretkey
      remoteRef:
        key: K8UP_S3_SECRET_KEY