---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
spec:
  interval: 30m
  chart:
    spec:
      chart: k8up
      version: 4.8.6
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: k8up
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
values:
  k8up:
    envVars:
      - name: BACKUP_GLOBALS3ENDPOINT
        value: https://fsn1.your-objectstorage.com
      - name: BACKUP_GLOBALS3BUCKET
        value: homek8sbkp
      - name: BACKUP_GLOBALREPOPASSWORD
        valueFrom:
          secretKeyRef:
            name: k8up-secret
            key: repopass
      - name: BACKUP_GLOBALACCESSKEYID
        valueFrom:
          secretKeyRef:
            name: k8up-secret
            key: s3accesskey
      - name: BACKUP_GLOBALSECRETACCESSKEY
        valueFrom:
          secretKeyRef:
            name: k8up-secret
            key: s3secretkey