---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: scraperr
  namespace: scraperr
spec:
  interval: 30m
  url: https://jaypyles.github.io/helm/charts/scraperr