---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: scraperr
spec:
  parentRefs:
    - namespace: kube-system
      name: gateway
      sectionName: https
  hostnames:
    - crawl.mrtb.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: scraperr
          port: 80
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: scraperr-api
          port: 8000